# docker-compose.production.yml
version: '3'

volumes:
  pg_data_kittygram:
  static_kittygram:
  media_kittygram:

# Всё отличие — заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13
    container_name: kittygram_db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: dmsvalik/kittygram_backend
    env_file: .env
    volumes:
      - static_kittygram:/backend_static
      - media_kittygram:/app/media
  frontend:
    image: dmsvalik/kittygram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kittygram:/frontend_static
  gateway:
    image: dmsvalik/kittygram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_kittygram:/staticfiles/
      - media_kittygram:/app/media
    ports:
      - 9000:80